services:
  # 1. BAZA DANYCH POSTGRESQL
  db:
    image: postgres:15
    container_name: toxic_system_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. SERWER SZTUCZNEJ INTELIGENCJI
  ai_research:
    build: 
      context: ./ai_research
    container_name: toxic_system_ai
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ${MODEL_PATH}:/app/model:ro
    environment:
      - MODEL_PATH=/app/model
    restart: unless-stopped

  # 3. GŁOWNY BACKEND APLIKACJI
  backend:
    depends_on:
      - db
      - ai_research
    build: 
      context: ./backend_api
    container_name: toxic_system_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded_audio:/app/static/audio:z
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - ai_research_URL=http://ai_research:8001/analyze
    restart: unless-stopped

volumes:
  pgdata: